/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-04-10 09:53:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.student.vocab_002dlists;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.LinkedList;
import com.pbl3.model.VocabListsModel;

public final class vocab_002dlists_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.pbl3.model.VocabListsModel");
    _jspx_imports_classes.add("java.util.LinkedList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<title>Hello, world!</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<style>\n");
      out.write("h1 {\n");
      out.write("	margin-bottom: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".box {\n");
      out.write("	width: 250px;\n");
      out.write("	height: 300px;\n");
      out.write("	color: red;\n");
      out.write("	border: 1px solid red;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".modal-form .modal-header {\n");
      out.write("	flex-direction: column;\n");
      out.write("	/* justify-content: center; */\n");
      out.write("	align-items: center;\n");
      out.write("	position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".modal-form .modal-header .close {\n");
      out.write("	position: absolute;\n");
      out.write("	top: -2px;\n");
      out.write("	right: -2px;\n");
      out.write("	opacity: .5;\n");
      out.write("	background-color: black;\n");
      out.write("	color: aliceblue;\n");
      out.write("	border-radius: 50%;\n");
      out.write("	/* padding: 10px; */\n");
      out.write("	width: 32px;\n");
      out.write("	height: 32px;\n");
      out.write("	display: flex;\n");
      out.write("	align-items: center;\n");
      out.write("	justify-content: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".modal-form .modal-header .inner-image {\n");
      out.write("	height: 40px;\n");
      out.write("	width: auto;\n");
      out.write("	margin-bottom: 6px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".button {\n");
      out.write("	background: -webkit-linear-gradient(-30deg, #f57f20, #d62b08 100%);\n");
      out.write("	color: #fff;\n");
      out.write("	border-radius: 10px;\n");
      out.write("	border: 1px solid;\n");
      out.write("	padding: 10px 30px;\n");
      out.write("	width: 100%;\n");
      out.write("	font-weight: 600;\n");
      out.write("}\n");
      out.write("/*bo gốc cho form*/\n");
      out.write(".modal-form .modal-content {\n");
      out.write("	border-radius: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("textarea {\n");
      out.write("	width: 100%;\n");
      out.write("	height: 200px;\n");
      out.write("}\n");
      out.write("</style>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("		<h1 style=\"text-align: center;\">DAY LA TRANG DANH SACH TU VUNG</h1>\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-3\">\r\n");
      out.write("				<div class=\"box\">\r\n");
      out.write("					<!-- Button trigger modal -->\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\"\r\n");
      out.write("						data-target=\"#exampleModal\">Them DSTV</button>\r\n");
      out.write("\r\n");
      out.write("					<!-- Modal -->\r\n");
      out.write("					<div class=\"modal fade modal-form\" id=\"exampleModal\" tabindex=\"-1\"\r\n");
      out.write("						aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("						<div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("							<div class=\"modal-content\">\r\n");
      out.write("								<div class=\"modal-header\">\r\n");
      out.write("\r\n");
      out.write("									<h5 class=\"inner-title\" id=\"exampleModalLabel\">THEM DS TU\r\n");
      out.write("										VUNG</h5>\r\n");
      out.write("									<p class=\"inner-desc\"></p>\r\n");
      out.write("									<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("										aria-label=\"Close\">\r\n");
      out.write("										<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("									</button>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"modal-body\">\r\n");
      out.write("									<form method=\"post\" action=\"/MVC/vocab-lists/create\">\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col-12\">\r\n");
      out.write("\r\n");
      out.write("												<div class=\"form-group\">\r\n");
      out.write("													<input name=\"name\" type=\"text\" class=\"form-control\"\r\n");
      out.write("														placeholder=\"Ten\">\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<textarea name=\"desc\" id=\"\" cols=\"30\" rows=\"10\"></textarea>\r\n");
      out.write("\r\n");
      out.write("												<button class=\"button\">Gui Di</button>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</form>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			int i = 0;
			
      out.write("\r\n");
      out.write("			");

			for (VocabListsModel v : (LinkedList<VocabListsModel>) request.getAttribute("vocabListsModels")) {
			
      out.write("\r\n");
      out.write("			<a href=\"vocab-lists/vocab?listID=");
      out.print(v.getListID());
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-3\" id=\"vocabBox\">\r\n");
      out.write("					<div class=\"box\">\r\n");
      out.write("						<h5>");
      out.print(v.getNameList());
      out.write("</h5>\r\n");
      out.write("						<p>");
      out.print(v.getDescription());
      out.write("</p>\r\n");
      out.write("						<br> <a href=\"vocab-lists/delete?listID=");
      out.print(v.getListID());
      out.write("\">\r\n");
      out.write("							XOA </a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						");

						//**********************************************
						
      out.write("\r\n");
      out.write("						");

						i++;
						
      out.write("\r\n");
      out.write("						<!-- Button trigger modal -->\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\"\r\n");
      out.write("							data-target=\"#exampleModal");
      out.print(i);
      out.write("\">SUA</button>\r\n");
      out.write("\r\n");
      out.write("						</button>\r\n");
      out.write("\r\n");
      out.write("						<!-- Modal -->\r\n");
      out.write("						<div class=\"modal fade modal-form\" id=\"exampleModal");
      out.print(i);
      out.write("\"\r\n");
      out.write("							tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\"\r\n");
      out.write("							aria-hidden=\"true\">\r\n");
      out.write("							<div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("								<div class=\"modal-content\">\r\n");
      out.write("									<div class=\"modal-header\">\r\n");
      out.write("\r\n");
      out.write("										<h5 class=\"inner-title\" id=\"exampleModalLabel\">SUA DS TU\r\n");
      out.write("											VUNG</h5>\r\n");
      out.write("										<p class=\"inner-desc\"></p>\r\n");
      out.write("										<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("											aria-label=\"Close\">\r\n");
      out.write("											<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("										</button>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col-12\">\r\n");
      out.write("												<h1>day la form</h1>\r\n");
      out.write("\r\n");
      out.write("												<form action=\"/MVC/vocab-lists/edit\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("													<div class=\"row\">\r\n");
      out.write("														<div class=\"col-12\">\r\n");
      out.write("															<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("																<input type=\"text\" class=\"form-control\"\r\n");
      out.write("																	placeholder=\"Ten\" name=\"nameList\"\r\n");
      out.write("																	value=\"");
      out.print(v.getNameList());
      out.write("\">\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("																<input type=\"hidden\" name=\"listID\"\r\n");
      out.write("																	, value=\"");
      out.print(v.getListID());
      out.write("\">\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("																<input type=\"hidden\" name=\"userID\"\r\n");
      out.write("																	, value=\"");
      out.print(v.getUserID());
      out.write("\">\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("																<input type=\"hidden\" name=\"CourseID\"\r\n");
      out.write("																	, value=\"");
      out.print(v.getCourseID());
      out.write("\">\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<textarea name=\"description\" id=\"\" cols=\"30\" rows=\"2\">\r\n");
      out.write("                                    	");
      out.print(v.getDescription());
      out.write("\r\n");
      out.write("                                    </textarea>\r\n");
      out.write("															<button class=\"button\">Gui Di</button>\r\n");
      out.write("														</div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</form>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						");

						//**********************************************
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div> ");

 }
 
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"\r\n");
      out.write("		integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
