/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-04-12 18:03:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.student.vocab_002dlists;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.pbl3.model.UserModel;
import java.util.LinkedList;
import com.pbl3.model.VocabListsModel;
import com.pbl3.model.UserModel;
import com.pbl3.model.AccountModel;

public final class vocab_002dlists_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/views/student/vocab-lists/../re-use/footer.jsp", Long.valueOf(1712825133310L));
    _jspx_dependants.put("/views/student/vocab-lists/../re-use/header.jsp", Long.valueOf(1712944981254L));
    _jspx_dependants.put("/views/student/vocab-lists/../../../assets/css/style-vocablists.css", Long.valueOf(1712934491631L));
    _jspx_dependants.put("/views/student/vocab-lists/../../../assets/css/base.css", Long.valueOf(1712942710690L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.pbl3.model.AccountModel");
    _jspx_imports_classes.add("com.pbl3.model.UserModel");
    _jspx_imports_classes.add("com.pbl3.model.VocabListsModel");
    _jspx_imports_classes.add("java.util.LinkedList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write(" <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\" integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\"\r\n");
      out.write("    integrity=\"sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==\"\r\n");
      out.write("    crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\" integrity=\"sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <title>Study TOIEC</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<style>\n");
      out.write(" 	");
      out.write("\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');\r\n");
      out.write(":root\r\n");
      out.write("{\r\n");
      out.write("    --color-one:  #0EDC8D;\r\n");
      out.write("    --color-two: #04182B;\r\n");
      out.write("    --color-text: #888886;\r\n");
      out.write("    --font: 'Be Vietnam Pro', serif; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("    font-family: var(--font);\r\n");
      out.write("    color: var(--color-text);\r\n");
      out.write("}   \r\n");
      out.write("\r\n");
      out.write("*{\r\n");
      out.write("    font-family: var(--font), sans-serif;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write(" color: var(--color-two);\r\n");
      out.write("}\r\n");
      out.write("a:hover{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: var(--color-one);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("    max-width: 1296px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* button */\r\n");
      out.write(".button-main {\r\n");
      out.write("	background-color: var(--color-text);\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	padding: 10px 10px;\r\n");
      out.write("	font-size: 17px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	border: solid 2px var(--color-text);\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-main:hover {\r\n");
      out.write("	color: var(--color-text);\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-main-one {\r\n");
      out.write("	background-color: var(--color-one);\r\n");
      out.write("	border-color: var(--color-one);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-main-one:hover {\r\n");
      out.write("	color: var(--color-one);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-main-two {\r\n");
      out.write("	background-color: var(--color-two);\r\n");
      out.write("	border-color: var(--color-two);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-main-two:hover {\r\n");
      out.write("	color: var(--color-two);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-main-three {\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	border-color: var(--color-one);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-main-three:hover {\r\n");
      out.write("	border-color: var(--color-one);\r\n");
      out.write("	color: var(--color-one);\r\n");
      out.write("}\r\n");
      out.write("/*end button */\r\n");
      out.write("\r\n");
      out.write("/* loader*/\r\n");
      out.write("	.loader {\r\n");
      out.write("    position: fixed; /* Äáº·t vá» trÃ­ lÃ  cá» Äá»nh */\r\n");
      out.write("              top: 50%; /* ÄÆ°a loader lÃªn giá»¯a theo chiá»u dá»c */\r\n");
      out.write("              left: 50%; /* ÄÆ°a loader ra giá»¯a theo chiá»u ngang */\r\n");
      out.write("              transform: translate(-50%, -50%);\r\n");
      out.write("    width: 85px;\r\n");
      out.write("    height: 85px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-wrap: wrap;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-content: space-between;\r\n");
      out.write("    animation: loading-rotate 3s linear infinite;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .item {\r\n");
      out.write("    width: 40px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    display: block;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .item:nth-of-type(1) {\r\n");
      out.write("    background-color:#0EDC8D\r\n");
      out.write("    ;\r\n");
      out.write("    border-radius: 20px 20px 0 20px;\r\n");
      out.write("    border-left: #ffffff 4px solid;\r\n");
      out.write("    border-top: #f7f7f7 4px solid;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .item:nth-of-type(2) {\r\n");
      out.write("    background-color:#0EDC8D\r\n");
      out.write("    ;\r\n");
      out.write("    border-radius: 20px 20px 20px 0;\r\n");
      out.write("    border-right: #ffffff 4px solid;\r\n");
      out.write("    border-top: #f7f7f7 4px solid;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .item:nth-of-type(3) {\r\n");
      out.write("    background-color: #0EDC8D\r\n");
      out.write("    ;\r\n");
      out.write("    border-radius: 20px 0 20px 20px;\r\n");
      out.write("    border-left: #ffffff 4px solid;\r\n");
      out.write("    border-bottom: #f7f7f7 4px solid;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .item:nth-of-type(4) {\r\n");
      out.write("    background-color: #0EDC8D\r\n");
      out.write("    ;\r\n");
      out.write("    border-radius: 0 20px 20px 20px;\r\n");
      out.write("    border-right: #ffffff 4px solid;\r\n");
      out.write("    border-bottom: #f7f7f7 4px solid;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  @keyframes loading-rotate {\r\n");
      out.write("    0% {\r\n");
      out.write("      transform: scale(1) rotate(0);\r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("    20% {\r\n");
      out.write("      transform: scale(1) rotate(72deg);\r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("    40% {\r\n");
      out.write("      transform: scale(0.5) rotate(144deg);\r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("    60% {\r\n");
      out.write("      transform: scale(0.5) rotate(216deg);\r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("    80% {\r\n");
      out.write("      transform: scale(1) rotate(288deg);\r\n");
      out.write("    }\r\n");
      out.write("  \r\n");
      out.write("    100% {\r\n");
      out.write("      transform: scale(1) rotate(360deg);\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("/*end loader*/\r\n");
      out.write("\r\n");
      out.write("  	");
      out.write("@charset \"UTF-8\";\r\n");
      out.write("	/* header */\r\n");
      out.write("    header .button:hover{\r\n");
      out.write("        background: var(--color-one);\r\n");
      out.write("        transition: all 0.8s;\r\n");
      out.write("    }\r\n");
      out.write("    header .button{\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        padding: 4px 20px;\r\n");
      out.write("        background: white;\r\n");
      out.write("        color: var(--color-one);\r\n");
      out.write("        border: 2px solid #fff;\r\n");
      out.write("        border-radius: 7px;\r\n");
      out.write("    }\r\n");
      out.write("    .header{\r\n");
      out.write("        box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);\r\n");
      out.write("        /* position: fixed; */\r\n");
      out.write("        position: sticky;\r\n");
      out.write("        z-index: 99;\r\n");
      out.write("        top: -50.7px;\r\n");
      out.write("        /* top:0;\r\n");
      out.write("        left: 0; */\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    /* header-top */\r\n");
      out.write("    header.header.hidentop{\r\n");
      out.write("        top:-50.7px;\r\n");
      out.write("    }\r\n");
      out.write("    header .top-header{\r\n");
      out.write("        background: var(--color-one);\r\n");
      out.write("        padding: 10px 0;\r\n");
      out.write("        font-size: 13px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("    header .top-header .inner-wrap{\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("    }\r\n");
      out.write("    header  ul{\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    header .top-header ul li a{\r\n");
      out.write("        color: var(--color-one);\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        margin: 10px;\r\n");
      out.write("        padding: 3px 6px;\r\n");
      out.write("        border-radius: 3px;\r\n");
      out.write("    }\r\n");
      out.write("    /* header .top-header ul li:hover{\r\n");
      out.write("        transform: translateY(-10px);\r\n");
      out.write("        transition: all 0.5s;\r\n");
      out.write("    } */\r\n");
      out.write("    header .top-header ul li span{\r\n");
      out.write("        color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("    header .inner-wrap .inner-button a{\r\n");
      out.write("        color: #fff\r\n");
      out.write("    }\r\n");
      out.write("    header .inner-wrap .inner-button .button-one{\r\n");
      out.write("        color: var(--color-one);\r\n");
      out.write("        margin-left: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    header .inner-wrap .inner-button .button-one:hover{\r\n");
      out.write("        color: #fff\r\n");
      out.write("    }\r\n");
      out.write("    /* end header-top */\r\n");
      out.write("\r\n");
      out.write("    /* header-main */\r\n");
      out.write("        header .main-header .inner-main{\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("        }\r\n");
      out.write("        header .inner-main .inner-logo img{\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            width: auto;\r\n");
      out.write("        }\r\n");
      out.write("        header .inner-main{\r\n");
      out.write("            padding:20px 0;\r\n");
      out.write("        }\r\n");
      out.write("        .header .inner-main .inner-menu ul li{\r\n");
      out.write("            margin: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .header .inner-main ul a{\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: var(--color-two);\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            text-wrap: nowrap;\r\n");
      out.write("        }\r\n");
      out.write("        .header .inner-main ul a:hover{\r\n");
      out.write("            color: var(--color-one);\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        header .inner-user .inner-img{\r\n");
      out.write("            height: 60px;\r\n");
      out.write("            width: 60px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        header .inner-user .inner-img img{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: auto;\r\n");
      out.write("            object-fit:cover;\r\n");
      out.write("            aspect-ratio: 1/1;\r\n");
      out.write("        }\r\n");
      out.write("    /* end header-main */\r\n");
      out.write("    /* end header */\r\n");
      out.write("\r\n");
      out.write("    /* welcome */\r\n");
      out.write("    .welcome{\r\n");
      out.write("    background-image: url(https://demo.graygrids.com/themes/edugrids/assets/images/breadcrumb/breadcrumb-bg.jpg);\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    background-position: center;\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    padding: 100px 0;\r\n");
      out.write("    /* z-index: 2; */\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .welcome::before{\r\n");
      out.write("        content: \"\";\r\n");
      out.write("        background: #081828;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top:0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        opacity: 0.8;\r\n");
      out.write("    }\r\n");
      out.write("    .welcome .col-12{\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("    }\r\n");
      out.write("    .welcome .inner-main{\r\n");
      out.write("        position: relative;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        max-width: 65%;\r\n");
      out.write("    }\r\n");
      out.write("    .welcome .inner-title{\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        font-size: 50px;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        margin-top: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    .welcome .inner-desc{\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("    .welcome .inner-bar{\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        padding-top: 5px;\r\n");
      out.write("        padding-right: 40px;\r\n");
      out.write("        padding-left: 40px;\r\n");
      out.write("        background:var(--color-one);\r\n");
      out.write("        border-radius: 14px;\r\n");
      out.write("    }\r\n");
      out.write("    .welcome .button-two{\r\n");
      out.write("        display: inline-flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        width: 130px;\r\n");
      out.write("        height: 45px;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        margin: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .welcome .button-two::before{\r\n");
      out.write("        content: \"\";\r\n");
      out.write("        width: 130px;\r\n");
      out.write("        height: 45px;\r\n");
      out.write("        background: var(--color-one);\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        left: -130px;\r\n");
      out.write("        transition: all 0.7s;\r\n");
      out.write("    }\r\n");
      out.write("    .welcome .button-two:hover::before{\r\n");
      out.write("        transform: translateX(130px);\r\n");
      out.write("    }\r\n");
      out.write("    .welcome .button-2{\r\n");
      out.write("        background: var(--color-one);\r\n");
      out.write("    }\r\n");
      out.write("    .welcome .button-2::before{\r\n");
      out.write("        background: #fff;\r\n");
      out.write("    }\r\n");
      out.write("    .welcome .inner-button a {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        z-index: 10;\r\n");
      out.write("        width: 130px;\r\n");
      out.write("        height: 45px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("    }\r\n");
      out.write("    .welcome .inner-button .button1{\r\n");
      out.write("        color: var(--color-two);\r\n");
      out.write("        font-size: 15px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("    .welcome .inner-button .button1:hover{\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        transition: all 0.7s;\r\n");
      out.write("    }\r\n");
      out.write("    .welcome .inner-button .button2{\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        font-size: 15px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("    .welcome .inner-button .button2:hover{\r\n");
      out.write("        color: var(--color-two);\r\n");
      out.write("        transition: all 0.7s;\r\n");
      out.write("    }\r\n");
      out.write("    /* end welcome */\r\n");
      out.write("\r\n");
      out.write("    /*list-vocab*/\r\n");
      out.write("    .list-vocab{\r\n");
      out.write("        margin-top: 100px;\r\n");
      out.write("        /* padding-top: 50px; */\r\n");
      out.write("        padding-bottom: 100px;\r\n");
      out.write("        /* background: #dcffe3; */\r\n");
      out.write("    }\r\n");
      out.write("    .list-vocab .col-xl-3{\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .list-vocab .col-xl-3 .inner-wrap{\r\n");
      out.write("        min-height: 100px;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        border: 1px solid #eee;\r\n");
      out.write("        padding:20px;\r\n");
      out.write("        transition: all 0.8s;\r\n");
      out.write("        box-shadow: 0 4px 0 0 rgba(143,156,173,.2);\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    .list-vocab .inner-wrap:hover{\r\n");
      out.write("        box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.2);\r\n");
      out.write("        transform: scale(1.07);\r\n");
      out.write("    }\r\n");
      out.write("    .list-vocab .inner-add{\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("    }\r\n");
      out.write("    .list-vocab .inner-add i{\r\n");
      out.write("        font-size: 50px;\r\n");
      out.write("    }\r\n");
      out.write("    .list-vocab .inner-img img{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        aspect-ratio: 12/7;\r\n");
      out.write("        object-fit:cover;\r\n");
      out.write("    }\r\n");
      out.write("    .list-vocab .inner-content{\r\n");
      out.write("        height:min-content;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .list-vocab .inner-content .inner-listname{\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        color: var(--color-two);\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        margin-top: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    .list-vocab .inner-content .inner-desc{\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        color: var(--color-two);\r\n");
      out.write("        margin-top: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    .list-vocab .inner-wrap .inner-number{\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        color: var(--color-text);\r\n");
      out.write("        padding-top:5px;\r\n");
      out.write("        border-top: 1px solid #eee;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        bottom: 10px;\r\n");
      out.write("        width: calc(100% - 40px);\r\n");
      out.write("    }\r\n");
      out.write("    .list-vocab .inner-wrap .inner-number p{\r\n");
      out.write("        margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("     \r\n");
      out.write("    /*end list-vocab*/\r\n");
      out.write("\r\n");
      out.write("          /* footer */\r\n");
      out.write("\r\n");
      out.write("          footer{\r\n");
      out.write("            margin-top: 150px;\r\n");
      out.write("            padding-top: 100px;\r\n");
      out.write("            border-top: 1px solid #eee;\r\n");
      out.write("        }\r\n");
      out.write("        footer .inner-img img{\r\n");
      out.write("\r\n");
      out.write("            width: 70%;\r\n");
      out.write("            height: auto;\r\n");
      out.write("        }\r\n");
      out.write("        footer .inner-intro .inner-desc{\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        footer .inner-intro .inner-list ul{\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        footer .inner-intro .inner-list ul i{\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            background: #eee;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("        }\r\n");
      out.write("        footer .inner-box h3{\r\n");
      out.write("            color: black;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        footer .inner-box a{\r\n");
      out.write("            color:var(--color-text);\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        footer .inner-box a:hover{\r\n");
      out.write("            color: var(--color-one);\r\n");
      out.write("        }\r\n");
      out.write("        footer .bottom-footer{\r\n");
      out.write("            margin-top: 100px;\r\n");
      out.write("            background: var(--color-one);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding:20px 0;\r\n");
      out.write("        }\r\n");
      out.write("        footer .bottom-footer p{\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: 400;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        /*end footer */\r\n");
      out.write("\r\n");
      out.write("        /* modal  */\r\n");
      out.write("        .list-vocab .modal .modal-header{\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            background: var(--color-one);\r\n");
      out.write("        }\r\n");
      out.write("        .list-vocab .modal-header h5{\r\n");
      out.write("            color: var(--color-two);\r\n");
      out.write("            font-size: 25px;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        .list-vocab .close{\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            right: 10px;\r\n");
      out.write("            font-size: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .list-vocab .close:hover{\r\n");
      out.write("            color: red;\r\n");
      out.write("            transform: scale(1.2);\r\n");
      out.write("            transition: all 0.2s;\r\n");
      out.write("        }\r\n");
      out.write("        .list-vocab .modal .form-group{\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            padding-left: 10%;\r\n");
      out.write("        }\r\n");
      out.write("        .list-vocab .modal .form-group label{\r\n");
      out.write("            color: var(--color-two);\r\n");
      out.write("        }\r\n");
      out.write("        .list-vocab .modal .form-group input{\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .list-vocab .modal .form-group textarea{\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .list-vocab .modal button{\r\n");
      out.write("            background-color: var(--color-one);\r\n");
      out.write("            border: 0;\r\n");
      out.write("            padding:5px 20px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        /* end  modal  */\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("</style>\r\n");
      out.write("<style>\n");
      out.write(".header .inner-main ul .tu-vung {\r\n");
      out.write("       		color: var(--color-one);\r\n");
      out.write("      	 }\n");
      out.write("</style>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write(" <header class=\"header\">\r\n");
      out.write("    <div class=\"top-header\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"inner-wrap\">\r\n");
      out.write("                <div class=\"inner-contact\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span>Following Us On:</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"https://www.facebook.com/Anhvubro/\" target=\"_blank\" >\r\n");
      out.write("                                <i class=\"fa-brands fa-facebook-f\" target=\"_blank\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\" >\r\n");
      out.write("                                <i class=\"fa-brands fa-twitter\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">\r\n");
      out.write("                                <i class=\"fa-brands fa-instagram\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"inner-button\">\r\n");
      out.write("                    <a href=\"#\">Create an Account</a>\r\n");
      out.write("                                      ");
 //lấy session
          UserModel userModel = (UserModel) session.getAttribute("user");
          // nếu session = null thì chưa đăng nhập nên dùng button đăng nhập
          if (userModel == null) {
      out.write("\r\n");
      out.write("                    <a href=\"/MVC/login\" class=\" button button-one\">Log In</a>\r\n");
      out.write("                    ");
 }
         // ngược lại là khác sesstion khác null : đã đăng nhập nên dùng button trang cá nhân 		
          else {
      out.write("\r\n");
      out.write("                    <a href=\"/MVC/logout\" class=\" button button-one\">Log Out</a>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main-header\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"inner-main\">\r\n");
      out.write("                <div class=\"inner-logo\">\r\n");
      out.write("                    <a href=\"/MVC/\">\r\n");
      out.write("                        <img src=\"https://scontent.fdad2-1.fna.fbcdn.net/v/t1.15752-9/433753477_1478956322991228_8817898143870258149_n.png?_nc_cat=101&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeHOQ56a-PhYUvmg0U6zPAXD66iRjloPIg_rqJGOWg8iD5T35I3AeoGiHZnS-gexmUk8wy4flOwyMiI4q1HxpQTc&_nc_ohc=th6U7HCRyugAb4g9_EP&_nc_ht=scontent.fdad2-1.fna&oh=03_AdVriVWV4qHki7K7WO-GATc15X6Hf5KtCJKNTChvo4ZE3g&oe=66378D9F\" alt=\"logo\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"inner-menu\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li> \r\n");
      out.write("                            <a href=\"/MVC/\" class=\"trang-chu\">\r\n");
      out.write("                                Trang Chủ\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li> \r\n");
      out.write("                            <a href=\"#\" class=\"khoa-hoc\">\r\n");
      out.write("                                Khóa Học\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li> \r\n");
      out.write("                            <a href=\"/MVC/tests\" class=\"de-thi\">\r\n");
      out.write("                                Đề Thi\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li> \r\n");
      out.write("                            <a href=\"/MVC/vocab-lists\" class=\"tu-vung\">\r\n");
      out.write("                                Từ Vựng\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"inner-user\">\r\n");
      out.write("                    <a href=\"/MVC/my-account\">\r\n");
      out.write("                        <div class=\"inner-img\">\r\n");
      out.write("                        	<img src=\"https://static.fireant.vn/users/avatar/d179d522-ea70-4c9c-8267-b2b0a58d5701?width=200&height=200\"  alt=\"avatar\">   \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"welcome\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"inner-main\">\r\n");
      out.write("                        <h2 class=\"inner-title\">Từ Vựng</h2>\r\n");
      out.write("                        <div class=\"inner-bar\"></div>\r\n");
      out.write("                        <p class=\"inner-desc\">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vel reprehenderit molestiae perspiciatis asperiores. Qui assumenda nostrum ipsa quos ad excepturi alias, molestias fuga odit, repellendus laudantium eum consequuntur, quo velit!</p>\r\n");
      out.write("                        <div class=\"inner-button\">\r\n");
      out.write("                            <!-- <div class=\"button-two button-1\">\r\n");
      out.write("                                    <a href=\"#\"class=\"button1\">Khóa Học</a>\r\n");
      out.write("                            </div> -->\r\n");
      out.write("                            <div class=\"button-two button-2\">\r\n");
      out.write("                                    <a href=\"#\"class=\"button2\" method=\"post\">Học Từ Vựng</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("        <div class=\"list-vocab\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xl-3\">\r\n");
      out.write("                    <!-- Button trigger modal -->\r\n");
      out.write("                    <a class=\"button-add\" data-toggle=\"modal\" data-target=\"#add-listvocab\">\r\n");
      out.write("                        <div class=\"inner-wrap inner-add\">\r\n");
      out.write("                        <i class=\"fa-solid fa-plus\"></i>\r\n");
      out.write("                        <p>Tạo danh sách từ vựng</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                             <!-- Modal -->\r\n");
      out.write("                            <div class=\"modal fade modal-form\" id=\"add-listvocab\" tabindex=\"-1\"\r\n");
      out.write("                            aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                            <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("                                <div class=\"modal-content\">\r\n");
      out.write("                                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("                                    aria-label=\"Close\">\r\n");
      out.write("                                    <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                    <div class=\"modal-header\">\r\n");
      out.write("                                        <h5 class=\"inner-title\" id=\"add-listvocab\">Thêm danh sách</h5>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"modal-body\">\r\n");
      out.write("                                        <form method=\"post\" action=\"/MVC/vocab-lists/create\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-12\">\r\n");
      out.write("                                                    <div class=\"form-group\">\r\n");
      out.write("                                                        <label for=\"ten\">Tên danh sách*:</label>\r\n");
      out.write("                                                        <input id=\"ten\" name=\"name\" type=\"text\" required>\r\n");
      out.write("                                                        <label for=\"mo-ta\">Mô tả:</label>\r\n");
      out.write("                                                        <textarea id=\"mo-ta\" name=\"desc\"></textarea>\r\n");
      out.write("                                                        <label for=\"anh\">Ảnh mô tả:</label>\r\n");
      out.write("                                                        <input id=\"anh\" type=\"file\" name=\"pic\">\r\n");
      out.write("                                                        <button class=\"button\">Thêm</button>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");

			int i = 0;
			
      out.write("\r\n");
      out.write("			");

			for (VocabListsModel v : (LinkedList<VocabListsModel>) request.getAttribute("vocabListsModels")) {
			
      out.write("\r\n");
      out.write("                <div class=\"col-xl-3\">\r\n");
      out.write("                    <a href=\"vocab-lists/vocab?listID=");
      out.print(v.getListID());
      out.write("\">\r\n");
      out.write("                        <div class=\"inner-wrap\">\r\n");
      out.write("                            <div class=\"inner-img\">\r\n");
      out.write("                                <img src=\"https://images.unsplash.com/photo-1581447109200-bf2769116351?q=80&w=1770&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D\" alt=\"listvocab\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"inner-content\">\r\n");
      out.write("                                <h3 class=\"inner-listname\">\r\n");
      out.write("                                    ");
      out.print(v.getNameList());
      out.write("\r\n");
      out.write("                                </h3>\r\n");
      out.write("                                <p class=\"inner-desc\">");
      out.print(v.getDescription());
      out.write("</p>\r\n");
      out.write("                                <!-- <p class=\"inner-number\">số lượng</p> -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"inner-number\">\r\n");
      out.write("                                <span>số lượng</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("             ");

 				}
 			 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-xl-3\">\r\n");
      out.write("				<div class=\"inner-intro\">\r\n");
      out.write("					<div class=\"inner-img\">\r\n");
      out.write("						<img\r\n");
      out.write("							src=\"https://scontent.fdad2-1.fna.fbcdn.net/v/t1.15752-9/433753477_1478956322991228_8817898143870258149_n.png?_nc_cat=101&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeHOQ56a-PhYUvmg0U6zPAXD66iRjloPIg_rqJGOWg8iD5T35I3AeoGiHZnS-gexmUk8wy4flOwyMiI4q1HxpQTc&_nc_ohc=th6U7HCRyugAb4g9_EP&_nc_ht=scontent.fdad2-1.fna&oh=03_AdVriVWV4qHki7K7WO-GATc15X6Hf5KtCJKNTChvo4ZE3g&oe=66378D9F\"\r\n");
      out.write("							alt=\"logo\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<p class=\"inner-desc\">© 2024</p>\r\n");
      out.write("					<div class=\"inner-list\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\"> <i class=\"fa-brands fa-facebook-f\"></i>\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a href=\"#\"> <i class=\"fa-brands fa-twitter\"></i>\r\n");
      out.write("							</a></li>\r\n");
      out.write("							<li><a href=\"#\"> <i class=\"fa-brands fa-instagram\"></i>\r\n");
      out.write("							</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-xl-3\">\r\n");
      out.write("				<div class=\"inner-box\">\r\n");
      out.write("					<h3 class=\".inner-title\">Về StudyTOEIC</h3>\r\n");
      out.write("					<a href=\"#\">Về chúng tôi</a> <a href=\"#\">Điều khoản dịch vụ</a> <a\r\n");
      out.write("						href=\"#\">Chính sách bảo mật</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-xl-3\">\r\n");
      out.write("				<div class=\"inner-box\">\r\n");
      out.write("					<h3 class=\".inner-title\">Thông tin StudyTOEIC</h3>\r\n");
      out.write("					<a href=\"#\">Danh sách khóa học</a> <a href=\"tests\">Danh sách đề\r\n");
      out.write("						thi</a> <a href=\"#\">Hướng dẫn thanh toán</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-xl-3\">\r\n");
      out.write("				<div class=\"inner-box\">\r\n");
      out.write("					<h3 class=\".inner-title\">Hỗ trợ</h3>\r\n");
      out.write("					<a href=\"#\">Hướng dẫn sử dụng khóa học</a> <a href=\"#\">Câu hỏi\r\n");
      out.write("						thường gặp</a> <a href=\"#\">Liên hệ</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"bottom-footer\">\r\n");
      out.write("		<p>@ 2024 - Bản quyền thuộc về nhóm 68</p>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"\r\n");
      out.write("		integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
