/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-05-04 04:23:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.student.vocab_002dlists.vocab;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.pbl3.model.VocabListsModel;
import java.util.LinkedList;
import com.pbl3.model.VocabModel;
import com.pbl3.model.UserModel;
import com.pbl3.model.AccountModel;

public final class reviewed_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/student/vocab-lists/vocab/../../../../assets/css/styleReviewed.css", Long.valueOf(1713809598031L));
    _jspx_dependants.put("/views/student/vocab-lists/vocab/../../../../assets/css/base.css", Long.valueOf(1714745199098L));
    _jspx_dependants.put("/views/student/vocab-lists/vocab/../../re-use/header.jsp", Long.valueOf(1713862799904L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(5);
    _jspx_imports_classes.add("com.pbl3.model.AccountModel");
    _jspx_imports_classes.add("com.pbl3.model.UserModel");
    _jspx_imports_classes.add("com.pbl3.model.VocabModel");
    _jspx_imports_classes.add("com.pbl3.model.VocabListsModel");
    _jspx_imports_classes.add("java.util.LinkedList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\" integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\"\r\n");
      out.write("    integrity=\"sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==\"\r\n");
      out.write("    crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\" integrity=\"sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    \r\n");
      out.write("    <title>Study TOIEC</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("    	");
      out.write("\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');\r\n");
      out.write(":root\r\n");
      out.write("{\r\n");
      out.write("    --color-one:  #0EDC8D;\r\n");
      out.write("    --color-two: #04182B;\r\n");
      out.write("    --color-text: #888886;\r\n");
      out.write("    --font: 'Be Vietnam Pro', serif; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a{ \r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("   \r\n");
      out.write("body{\r\n");
      out.write("    font-family: var(--font);\r\n");
      out.write("    color: var(--color-text);\r\n");
      out.write("}   \r\n");
      out.write("\r\n");
      out.write("*{\r\n");
      out.write("    font-family: var(--font), sans-serif;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write(" color: var(--color-two);\r\n");
      out.write("}\r\n");
      out.write("a:hover{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: var(--color-one);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("    max-width: 1400px; \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("/* button */\r\n");
      out.write(".button-main {\r\n");
      out.write("	background-color: var(--color-text);\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	padding: 10px 10px;\r\n");
      out.write("	font-size: 17px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	border: solid 2px var(--color-text);\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-main:hover {\r\n");
      out.write("	color: var(--color-text);\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-main-one {\r\n");
      out.write("	background-color: var(--color-one);\r\n");
      out.write("	border-color: var(--color-one);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-main-one:hover {\r\n");
      out.write("	color: var(--color-one);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-main-two {\r\n");
      out.write("	background-color: var(--color-two);\r\n");
      out.write("	border-color: var(--color-two);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-main-two:hover {\r\n");
      out.write("	color: var(--color-two);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-main-three {\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	border-color: var(--color-one);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-main-three:hover {\r\n");
      out.write("	border-color: var(--color-one);\r\n");
      out.write("	color: var(--color-one);\r\n");
      out.write("}\r\n");
      out.write("/*end button */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    	 ");
      out.write(".container{\r\n");
      out.write("    max-width: 768px;\r\n");
      out.write("}\r\n");
      out.write("    header .container{\r\n");
      out.write("        max-width: 1296px;\r\n");
      out.write("    }\r\n");
      out.write("    footer .container{\r\n");
      out.write("        max-width: 1296px;\r\n");
      out.write("    }\r\n");
      out.write("/* header */\r\n");
      out.write("header .button:hover{\r\n");
      out.write("    background: var(--color-one);\r\n");
      out.write("    transition: all 0.8s;\r\n");
      out.write("}\r\n");
      out.write("header .button{\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 4px 20px;\r\n");
      out.write("    background: white;\r\n");
      out.write("    color: var(--color-one);\r\n");
      out.write("    border: 2px solid #fff;\r\n");
      out.write("    border-radius: 7px;\r\n");
      out.write("}\r\n");
      out.write(".header{\r\n");
      out.write("    box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);\r\n");
      out.write("    /* position: fixed; */\r\n");
      out.write("    position: sticky;\r\n");
      out.write("    z-index: 99;\r\n");
      out.write("    top: -50.7px;\r\n");
      out.write("    /* top:0;\r\n");
      out.write("    left: 0; */\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* header-top */\r\n");
      out.write("header.header.hidentop{\r\n");
      out.write("    top:-50.7px;\r\n");
      out.write("}\r\n");
      out.write("header .top-header{\r\n");
      out.write("    background: var(--color-one);\r\n");
      out.write("    padding: 10px 0;\r\n");
      out.write("    font-size: 13px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("header .top-header .inner-wrap{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("header  ul{\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("header .top-header ul li a{\r\n");
      out.write("    color: var(--color-one);\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    margin: 10px;\r\n");
      out.write("    padding: 3px 6px;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("}\r\n");
      out.write("/* header .top-header ul li:hover{\r\n");
      out.write("    transform: translateY(-10px);\r\n");
      out.write("    transition: all 0.5s;\r\n");
      out.write("} */\r\n");
      out.write("header .top-header ul li span{\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("header .inner-wrap .inner-button a{\r\n");
      out.write("    color: #fff\r\n");
      out.write("}\r\n");
      out.write("header .inner-wrap .inner-button .button-one{\r\n");
      out.write("    color: var(--color-one);\r\n");
      out.write("    margin-left: 15px;\r\n");
      out.write("}\r\n");
      out.write("header .inner-wrap .inner-button .button-one:hover{\r\n");
      out.write("    color: #fff\r\n");
      out.write("}\r\n");
      out.write("/* end header-top */\r\n");
      out.write("\r\n");
      out.write("/* header-main */\r\n");
      out.write("    header .main-header .inner-main{\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("    }\r\n");
      out.write("    header .inner-main .inner-logo img{\r\n");
      out.write("        height: 40px;\r\n");
      out.write("        width: auto;\r\n");
      out.write("    }\r\n");
      out.write("    header .inner-main{\r\n");
      out.write("        padding:20px 0;\r\n");
      out.write("    }\r\n");
      out.write("    .header .inner-main .inner-menu ul li{\r\n");
      out.write("        margin: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    .header .inner-main ul a{\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        color: var(--color-two);\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        text-wrap: nowrap;\r\n");
      out.write("    }\r\n");
      out.write("    .header .inner-main ul a:hover{\r\n");
      out.write("        color: var(--color-one);\r\n");
      out.write("        transition: all 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    header .inner-user .inner-img{\r\n");
      out.write("        height: 60px;\r\n");
      out.write("        width: 60px;\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("    header .inner-user .inner-img img{\r\n");
      out.write("        width: 13rem;\r\n");
      out.write("        height: auto;  \r\n");
      out.write("        object-fit:cover;\r\n");
      out.write("        aspect-ratio: 1/1;\r\n");
      out.write("    }\r\n");
      out.write("/* end header-main */\r\n");
      out.write("/* end header */\r\n");
      out.write("body{\r\n");
      out.write("    background: #F8F9FA;\r\n");
      out.write("}\r\n");
      out.write(".flashcard {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 350px;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    transition: transform 0.8s;\r\n");
      out.write("    transform-style: preserve-3d;\r\n");
      out.write("    border: 1px solid #cccccc;\r\n");
      out.write("    box-shadow: 0 4px 0 0 rgba(143, 156, 173, .2);\r\n");
      out.write("}\r\n");
      out.write(".flashcard.onclick  {\r\n");
      out.write("    transform: rotateY(180deg); \r\n");
      out.write("}\r\n");
      out.write(".inner-main .flashcard:first-child{\r\n");
      out.write("    display: block;\r\n");
      out.write("}\r\n");
      out.write(".flashcard{\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".front\r\n");
      out.write("{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    backface-visibility: hidden;\r\n");
      out.write("}\r\n");
      out.write(".front h2{\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    color: black;\r\n");
      out.write("}\r\n");
      out.write(".front .inner-vocabtype h3{\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    color: black;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".front audio{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    visibility: hidden;\r\n");
      out.write("}\r\n");
      out.write(".front .playButton{\r\n");
      out.write("    font-size: 25px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    color: #00a463;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 4px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    z-index: 10;\r\n");
      out.write("}\r\n");
      out.write(".back {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    backface-visibility: hidden;\r\n");
      out.write("    padding:20px;\r\n");
      out.write("}\r\n");
      out.write(".back .col-8{\r\n");
      out.write("    max-height: 300px;\r\n");
      out.write("}\r\n");
      out.write(".back .inner-mean{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    overflow-y: scroll;\r\n");
      out.write("}\r\n");
      out.write(".back h5{\r\n");
      out.write("    color: black;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("}\r\n");
      out.write(".back p{\r\n");
      out.write("    color: rgb(32, 32, 32);\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-weight: 300;\r\n");
      out.write("}\r\n");
      out.write(".back ul li{\r\n");
      out.write("    color: black;\r\n");
      out.write("}\r\n");
      out.write(".back img{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    aspect-ratio: 4/3;\r\n");
      out.write("    object-fit: cover;\r\n");
      out.write("}\r\n");
      out.write(".front {\r\n");
      out.write("    z-index: 2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".back {\r\n");
      out.write("    transform: rotateY(180deg);\r\n");
      out.write("}\r\n");
      out.write(".section-one{\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write(".section-one .inner-title h2{\r\n");
      out.write("    color: black;\r\n");
      out.write("    font-size: 32px;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write(".section-one .inner-controlpage{\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write(".section-one .inner-controlpage a:first-child{\r\n");
      out.write("    color: var(--color-one);\r\n");
      out.write("}\r\n");
      out.write(".section-one .inner-controlpage a:last-child{\r\n");
      out.write("    color:red;\r\n");
      out.write("}\r\n");
      out.write(".section-two{\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write(".section-three .inner-controler{\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: right;\r\n");
      out.write("    padding:25px;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    border: 1px solid #cccccc;\r\n");
      out.write("    box-shadow: 0 4px 0 0 rgba(143, 156, 173, .2);\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write(".inner-notifi p{\r\n");
      out.write("    margin-top: 100px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    color: black;\r\n");
      out.write("    font-weight: 300;\r\n");
      out.write("    font-style: italic;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inner-controler button {\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  border: 1px solid #fff;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  color: #3c4043;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  font-weight: 500;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  user-select: none;\r\n");
      out.write("  -webkit-user-select: none;\r\n");
      out.write("  touch-action: manipulation;\r\n");
      out.write("  white-space: pre;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inner-controler button:hover {\r\n");
      out.write("  border-color: #dadce0;\r\n");
      out.write("  box-shadow: rgba(0, 0, 0, .1) 0 1px 1px;\r\n");
      out.write("  color: var(--color-one);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /* footer */\r\n");
      out.write("\r\n");
      out.write("        footer{\r\n");
      out.write("            margin-top: 150px;\r\n");
      out.write("            padding-top: 100px;\r\n");
      out.write("            border-top: 1px solid #eee;\r\n");
      out.write("            background:#fff;\r\n");
      out.write("        }\r\n");
      out.write("        footer .inner-img img{\r\n");
      out.write("\r\n");
      out.write("            width: 70%;\r\n");
      out.write("            height: auto;\r\n");
      out.write("        }\r\n");
      out.write("        footer .inner-intro .inner-desc{\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        footer .inner-intro .inner-list ul{\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        footer .inner-intro .inner-list ul i{\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            background: #eee;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("        }\r\n");
      out.write("        footer .inner-box h3{\r\n");
      out.write("            color: black;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        footer .inner-box a{\r\n");
      out.write("            color:var(--color-text);\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        footer .inner-box a:hover{\r\n");
      out.write("            color: var(--color-one);\r\n");
      out.write("        }\r\n");
      out.write("        footer .bottom-footer{\r\n");
      out.write("            margin-top: 100px;\r\n");
      out.write("            background: var(--color-one);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding:20px 0;\r\n");
      out.write("        }\r\n");
      out.write("        footer .bottom-footer p{\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: 400;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("        /*end footer */");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("    <!-- header  -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write(" <header class=\"header\">\r\n");
      out.write("    <div class=\"top-header\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"inner-wrap\">\r\n");
      out.write("                <div class=\"inner-contact\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <span>Following Us On:</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"https://www.facebook.com/Anhvubro/\" target=\"_blank\" >\r\n");
      out.write("                                <i class=\"fa-brands fa-facebook-f\" target=\"_blank\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\" >\r\n");
      out.write("                                <i class=\"fa-brands fa-twitter\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\" target=\"_blank\">\r\n");
      out.write("                                <i class=\"fa-brands fa-instagram\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"inner-button\">\r\n");
      out.write("                    <a href=\"#\">Create an Account</a>\r\n");
      out.write("                                      ");
 //lấy session
          UserModel userModel = (UserModel) session.getAttribute("user");
          // nếu session = null thì chưa đăng nhập nên dùng button đăng nhập
          if (userModel == null) {
      out.write("\r\n");
      out.write("                    <a href=\"/MVC/login\" class=\" button button-one\">Log In</a>\r\n");
      out.write("                    ");
 }
         // ngược lại là khác sesstion khác null : đã đăng nhập nên dùng button trang cá nhân 		
          else {
      out.write("\r\n");
      out.write("                    <a href=\"/MVC/logout\" class=\" button button-one\">Log Out</a>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main-header\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"inner-main\">\r\n");
      out.write("                <div class=\"inner-logo\">\r\n");
      out.write("                    <a href=\"/MVC/\">\r\n");
      out.write("                        <img src=\"https://scontent.fdad2-1.fna.fbcdn.net/v/t1.15752-9/433753477_1478956322991228_8817898143870258149_n.png?_nc_cat=101&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeHOQ56a-PhYUvmg0U6zPAXD66iRjloPIg_rqJGOWg8iD5T35I3AeoGiHZnS-gexmUk8wy4flOwyMiI4q1HxpQTc&_nc_ohc=th6U7HCRyugAb4g9_EP&_nc_ht=scontent.fdad2-1.fna&oh=03_AdVriVWV4qHki7K7WO-GATc15X6Hf5KtCJKNTChvo4ZE3g&oe=66378D9F\" alt=\"logo\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"inner-menu\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li> \r\n");
      out.write("                            <a href=\"/MVC/\" class=\"trang-chu\">\r\n");
      out.write("                                Trang Chủ\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li> \r\n");
      out.write("                            <a href=\"/MVC/courses\" class=\"khoa-hoc\"> \r\n");
      out.write("                                Khóa Học  \r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li> \r\n");
      out.write("                            <a href=\"/MVC/tests\" class=\"de-thi\">\r\n");
      out.write("                                Đề Thi\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li> \r\n");
      out.write("                            <a href=\"/MVC/vocab-lists\" class=\"tu-vung\">\r\n");
      out.write("                                Từ Vựng\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"inner-user\">\r\n");
      out.write("                    <a href=\"/MVC/my-account\">\r\n");
      out.write("                        <div class=\"inner-img\">\r\n");
      out.write("                        	<img src=\"https://scontent.fdad3-1.fna.fbcdn.net/v/t1.15752-9/438271424_363628142750726_982160961036786015_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeHkYs5D6zVd2CobOzv17Q-CghzjkuK_nIiCHOOS4r-ciPpq3LA3YzM8SDgsA1cd9eiwpRC36kSmzjm0TzN1lUsC&_nc_ohc=poSTrCaVAV0Ab7PCeUg&_nc_ht=scontent.fdad3-1.fna&oh=03_Q7cD1QEqPf93u7Qm4giDR7jfyN0LaJfqodwt601AMFz9Bqc6hA&oe=664ED094\"  alt=\"avatar\">   \r\n");
      out.write("                        </div> \r\n");
      out.write("                    </a> \r\n");
      out.write("                </div>    \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("    <!--end  header  -->\r\n");
      out.write("    ");
 VocabListsModel vocabListsModel =(VocabListsModel)request.getAttribute("vocablistsModel");
    LinkedList<VocabModel> vocabModels =(LinkedList<VocabModel>) request.getAttribute("vocabModels");
    int listID=(int) request.getAttribute("listID");
    
      out.write("\r\n");
      out.write("     <div class=\"section-one\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"inner-title\">\r\n");
      out.write("                <h2>Ôn tập: ");
      out.print(vocabListsModel.getNameList() );
      out.write("</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"inner-controlpage\">\r\n");
      out.write("                <a class=\"back-list\"href=\"/MVC/vocab-lists/vocab/review?action=learn&listID=");
      out.print(vocabListsModel.getListID() );
      out.write("\"> <i class=\"fa-brands fa-leanpub\"></i>  Học từ mới</a>\r\n");
      out.write("                <a class=\"stop-review\" href=\"/MVC/vocab-lists/vocab?listID=");
      out.print(vocabListsModel.getListID() );
      out.write("\"><i class=\"fa-regular fa-rectangle-xmark\"></i>   Dừng học danh sách này</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
if(vocabModels.size()!=0){ 
      out.write("\r\n");
      out.write("    <div class=\"section-two\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"inner-main\" id=\"flashcard\">\r\n");
      out.write("            ");
for (VocabModel v : vocabModels){ 
      out.write("\r\n");
      out.write("                <div class=\"flashcard\" >\r\n");
      out.write("                    <div class=\"front\">\r\n");
      out.write(" 						<div class=\"inner-englishmean\">\r\n");
      out.write("                            <h2>");
      out.print(v.getVocab() );
      out.write("\r\n");
      out.write("                                <a class=\"playButton\">\r\n");
      out.write("                                    <i class=\"fa-solid fa-volume-high\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <audio class=\"myAudio\" src=\"https://dict.youdao.com/dictvoice?audio=");
      out.print(v.getVocab() );
      out.write("&type=1\" type=\"audio/mpeg\" controls></audio>\r\n");
      out.write("                            </h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"inner-vocabtype\">\r\n");
      out.write("                            <h3>(");
      out.print(v.getWordType() );
      out.write(')');
      out.write(' ');
      out.write('/');
      out.print( v.getPronunciation());
      out.write("/</h3>\r\n");
      out.write("                        </div>  \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"back\">\r\n");
      out.write("						 <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-8\">\r\n");
      out.write("                                <div class=\"inner-mean\">\r\n");
      out.write("                                    <h5 >Định nghĩa:</h5>\r\n");
      out.write("                                    <p class=\"vietnam-mean\">");
      out.print(v.getMean() );
      out.write("</p>\r\n");
      out.write("                                    <h5 class=\"exam\">Ví dụ</h5>\r\n");
      out.write("                                    <div class=\"inner-ex\">\r\n");
      out.write("                                                        \r\n");
      out.write("                                                        ");
String[] parts = (v.getExample()).split("\\n"); 
      out.write("\r\n");
      out.write("                                                        <ul>\r\n");
      out.write("                                                            ");
for(String str : parts) {
      out.write("\r\n");
      out.write("                                                            	<li>\r\n");
      out.write("                                                            		");
      out.print(str);
      out.write("\r\n");
      out.write("                                                            	</li>	\r\n");
      out.write("                                                            ");
} 
      out.write("\r\n");
      out.write("                                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-4\">\r\n");
      out.write("                               ");
if(v.getImage() == null){ 
      out.write("\r\n");
      out.write("                                    	<img src=\"https://e-talk.vn/wp-content/uploads/2019/04/cach-hoc-tu-vung-tieng-anh-sieu-toc-1024x1024.png\" alt=\"Ảnh mô tả\">\r\n");
      out.write("                                	");
}else{
      out.write("\r\n");
      out.write("                                		\r\n");
      out.write("                                		<img alt=\"anh-mo-ta\" src=\"/MVC/");
      out.print(v.getImage());
      out.write("\">\r\n");
      out.write("                               		");
}
      out.write("  \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div> \r\n");
      out.write("					</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"section-three\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"inner-controler\">\r\n");
      out.write("                <button id=\"next-button\">Tiếp tục</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
} else{
      out.write("\r\n");
      out.write("    	    <div class=\"inner-notifi\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <p> Bạn chưa học được từ nào!</p>  \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("         <!-- <footer> -->\r\n");
      out.write("        <footer>\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-3\">\r\n");
      out.write("                        <div class=\"inner-intro\">\r\n");
      out.write("                            <div class=\"inner-img\">\r\n");
      out.write("                                <img src=\"https://scontent.fdad2-1.fna.fbcdn.net/v/t1.15752-9/433753477_1478956322991228_8817898143870258149_n.png?_nc_cat=101&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeHOQ56a-PhYUvmg0U6zPAXD66iRjloPIg_rqJGOWg8iD5T35I3AeoGiHZnS-gexmUk8wy4flOwyMiI4q1HxpQTc&_nc_ohc=th6U7HCRyugAb4g9_EP&_nc_ht=scontent.fdad2-1.fna&oh=03_AdVriVWV4qHki7K7WO-GATc15X6Hf5KtCJKNTChvo4ZE3g&oe=66378D9F\" alt=\"logo\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"inner-desc\">\r\n");
      out.write("                                © 2024\r\n");
      out.write("                            </p>\r\n");
      out.write("                        <div class=\"inner-list\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <i class=\"fa-brands fa-facebook-f\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <i class=\"fa-brands fa-twitter\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <i class=\"fa-brands fa-instagram\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-3\">\r\n");
      out.write("                        <div class=\"inner-box\">\r\n");
      out.write("                            <h3 class=\".inner-title\">\r\n");
      out.write("                                Về StudyTOEIC\r\n");
      out.write("                            </h3>\r\n");
      out.write("                            <a href=\"#\">Về chúng tôi</a>\r\n");
      out.write("                            <a href=\"#\">Điều khoản dịch vụ</a>\r\n");
      out.write("                            <a href=\"#\">Chính sách bảo mật</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-3\">\r\n");
      out.write("                        <div class=\"inner-box\">\r\n");
      out.write("                            <h3 class=\".inner-title\">\r\n");
      out.write("                                Thông tin StudyTOEIC\r\n");
      out.write("                            </h3>\r\n");
      out.write("                            <a href=\"#\">Danh sách khóa học</a>\r\n");
      out.write("                            <a href=\"tests\">Danh sách đề thi</a>\r\n");
      out.write("                            <a href=\"#\">Hướng dẫn thanh toán</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-3\">\r\n");
      out.write("                        <div class=\"inner-box\">\r\n");
      out.write("                            <h3 class=\".inner-title\">\r\n");
      out.write("                                Hỗ trợ\r\n");
      out.write("                            </h3>\r\n");
      out.write("                            <a href=\"#\">Hướng dẫn sử dụng khóa học</a>\r\n");
      out.write("                            <a href=\"#\">Câu hỏi thường gặp</a>\r\n");
      out.write("                            <a href=\"#\">Liên hệ</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"bottom-footer\">\r\n");
      out.write("                <p>@ 2024 - Bản quyền thuộc về nhóm 68</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- end footer -->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct\" crossorigin=\"anonymous\"></script> \r\n");
      out.write("        <script>\r\n");
      out.write("        //click audio\r\n");
      out.write("        var audioElements = document.querySelectorAll(\".myAudio\");\r\n");
      out.write("        var playButtons = document.querySelectorAll(\".playButton\");\r\n");
      out.write("\r\n");
      out.write("        // Duyệt qua mỗi cặp phần tử audio và nút\r\n");
      out.write("        playButtons.forEach(function(playButton, index) {\r\n");
      out.write("            var audio = audioElements[index];\r\n");
      out.write("\r\n");
      out.write("        // Thêm sự kiện click cho mỗi nút\r\n");
      out.write("        playButton.addEventListener(\"click\", function(event) {\r\n");
      out.write("            event.stopPropagation();\r\n");
      out.write("            if (audio.paused) {\r\n");
      out.write("                audio.play(); // Nếu đang tạm dừng, tiếp tục phát\r\n");
      out.write("            } else {\r\n");
      out.write("                audio.pause(); // Nếu đang phát, tạm dừng\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("        // Định nghĩa hàm để xử lý sự kiện click\r\n");
      out.write("        function handleClick(event) {\r\n");
      out.write("            // Lấy tất cả các phần tử có class 'myButtons'\r\n");
      out.write("            var buttons = document.querySelectorAll('.flashcard');\r\n");
      out.write("            // Lặp qua từng phần tử và thực hiện thay đổi\r\n");
      out.write("            buttons.forEach(function(button) {\r\n");
      out.write("                // Kiểm tra xem class 'highlight' đã tồn tại trên phần tử hay chưa\r\n");
      out.write("                if (button.classList.contains('onclick')) {\r\n");
      out.write("                    // Nếu đã tồn tại, loại bỏ class 'highlight'\r\n");
      out.write("                    button.classList.remove('onclick');\r\n");
      out.write("                } else {\r\n");
      out.write("                    // Nếu chưa tồn tại, thêm class 'highlight'\r\n");
      out.write("                    button.classList.add('onclick');\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        //hàm trả về front\r\n");
      out.write("        function front() {\r\n");
      out.write("                var buttons = document.querySelectorAll('.flashcard');\r\n");
      out.write("                buttons.forEach(function(button) {\r\n");
      out.write("                    if (button.classList.contains('onclick')) {\r\n");
      out.write("                        button.classList.remove('onclick');\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            );\r\n");
      out.write("            }\r\n");
      out.write("        document.getElementById('flashcard').addEventListener('click', handleClick);\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        window.addEventListener('load', random);\r\n");
      out.write("        document.getElementById('next-button').addEventListener('click', random);\r\n");
      out.write("        function random() {\r\n");
      out.write("        var contents = document.getElementsByClassName('flashcard');\r\n");
      out.write("        var maxLength =");
      out.print(vocabModels.size());
      out.write(";\r\n");
      out.write("        var randomIndex = Math.floor(Math.random() * maxLength);\r\n");
      out.write("		front();\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        // Ẩn tất cả các nội dung\r\n");
      out.write("        for (var i = 0; i < maxLength; i++) {\r\n");
      out.write("            contents[i].style.display = 'none';\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Hiển thị nội dung ngẫu nhiên được chọn\r\n");
      out.write("        contents[randomIndex].style.display = 'block';\r\n");
      out.write("        if (audioElements[randomIndex].paused) {\r\n");
      out.write("        	audioElements[randomIndex].play(); // Nếu đang tạm dừng, tiếp tục phát\r\n");
      out.write("        } else {\r\n");
      out.write("        	audioElements[randomIndex].pause(); // Nếu đang phát, tạm dừng\r\n");
      out.write("        }\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("            $(window).scroll(function(){\r\n");
      out.write("                if($(this).scrollTop()){\r\n");
      out.write("                    $('header').addClass('hidentop');\r\n");
      out.write("                }\r\n");
      out.write("                else\r\n");
      out.write("                $('header').removeClass('hidentop');\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        </script>\r\n");
      out.write("      </body>\r\n");
      out.write("    </html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
