/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-05-05 13:02:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin.coupon;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.pbl3.libs.Pair;
import com.pbl3.model.UserModel;
import java.util.LinkedList;
import com.pbl3.model.CourseModel;

public final class coupon_002dcourse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/views/admin/coupon/../re-use/header.jsp", Long.valueOf(1714727470079L));
    _jspx_dependants.put("/views/admin/coupon/../../../assets/admin-css/base.css", Long.valueOf(1714836824483L));
    _jspx_dependants.put("/views/admin/coupon/../../../assets/admin-css/style-createCourse.css", Long.valueOf(1714735714535L));
    _jspx_dependants.put("/views/admin/coupon/../../../assets/admin-css/style-course.css", Long.valueOf(1714733172181L));
    _jspx_dependants.put("/views/admin/coupon/../re-use/sidebar.jsp", Long.valueOf(1714727354402L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.pbl3.model.UserModel");
    _jspx_imports_classes.add("com.pbl3.libs.Pair");
    _jspx_imports_classes.add("java.util.LinkedList");
    _jspx_imports_classes.add("com.pbl3.model.CourseModel");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("	<style> \r\n");
      out.write("		");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');\r\n");
      out.write(":root{\r\n");
      out.write("    --color-one: #0EDC8D;\r\n");
      out.write("    --color-two: #04182B;\r\n");
      out.write("    --color-text: black;\r\n");
      out.write("    --font: 'Be Vietnam Pro', serif; \r\n");
      out.write("}\r\n");
      out.write(" *{\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" body{\r\n");
      out.write("    font-family: var(--font);\r\n");
      out.write("    color: var(--color-text);\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("/* menu */\r\n");
      out.write(".menu{\r\n");
      out.write("    background: var(--color-two);\r\n");
      out.write("    width: 220px;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    border-right: 3px solid var(--color-one);\r\n");
      out.write("}\r\n");
      out.write(".menu .logo{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    padding-left: 80px;\r\n");
      out.write("    padding-top: 18px;\r\n");
      out.write("}\r\n");
      out.write(".menu .logo i{\r\n");
      out.write("    width: 150px;\r\n");
      out.write("    margin-right: 15px;\r\n");
      out.write("    height: auto;\r\n");
      out.write("    object-fit: cover;\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-size: 40px;\r\n");
      out.write("}\r\n");
      out.write(".menu .logo:hover i{\r\n");
      out.write("    color: var(--color-one);\r\n");
      out.write("}\r\n");
      out.write(".menu .item{\r\n");
      out.write("    margin-top: 20px ;\r\n");
      out.write("    border-radius: 20px;\r\n");
      out.write("}\r\n");
      out.write(".menu .item li{\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    padding: 15px 0;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write(".menu .item li:hover{\r\n");
      out.write("    background:var(--color-one) ;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".menu .item li:nth-child(2){\r\n");
      out.write("    border-left: 4px solid white;\r\n");
      out.write("}\r\n");
      out.write(".menu .item li i{\r\n");
      out.write("    color: white;\r\n");
      out.write("    width: 30px;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    line-height: 30px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    margin: 0 10px 0 10px;\r\n");
      out.write("}\r\n");
      out.write(".menu .item li:hover i{\r\n");
      out.write("    color: var(--color-two);\r\n");
      out.write("}\r\n");
      out.write(".menu .item li a{\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: white ;\r\n");
      out.write("    font-weight: 300px;\r\n");
      out.write("}\r\n");
      out.write(".menu .item li:hover a{\r\n");
      out.write("    color: var(--color-two);\r\n");
      out.write("}\r\n");
      out.write("/* end menu */ \r\n");
      out.write("\r\n");
      out.write("/* main */\r\n");
      out.write("\r\n");
      out.write(".main{\r\n");
      out.write("    width: calc(100% - 220px);\r\n");
      out.write("    margin-left: 220px;\r\n");
      out.write("    background: white;\r\n");
      out.write("}\r\n");
      out.write(".main .header{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content:space-between;\r\n");
      out.write("    background: white;\r\n");
      out.write("    padding: 15px 30px;\r\n");
      out.write("    border-bottom: 3px solid var(--color-one);\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    width: calc(100% - 220px);\r\n");
      out.write("    z-index: 99;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main .header .search{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: flex-start;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    padding: 10px 14px;\r\n");
      out.write("    border: 1px solid var(--color-text);\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write(".main .header .search i{\r\n");
      out.write("    margin-right: 14px;\r\n");
      out.write("}\r\n");
      out.write(".main .header .search input{\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    font-size: 14px ;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main .header .profile{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: flex-start;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".main .header .profile i{\r\n");
      out.write("    margin-right: 20px;\r\n");
      out.write("    font-size: 19px;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("}\r\n");
      out.write(".main .header .profile img{\r\n");
      out.write("    width: 30px;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    object-fit: cover;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write(".name{\r\n");
      out.write("    margin-top: 70px;\r\n");
      out.write("    color: var(--color-two);\r\n");
      out.write("    padding: 30px 30px 0 30px ;\r\n");
      out.write("    font-size: 24px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("}     \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("th, td {\r\n");
      out.write("    padding: 8px;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    border-bottom: 1px solid #ddd;\r\n");
      out.write("}\r\n");
      out.write("th {\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("table{\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("tr{\r\n");
      out.write("    border-bottom: 1px solid var(--color-one);\r\n");
      out.write("}\r\n");
      out.write("td, th {\r\n");
      out.write("    vertical-align: middle; /* Äáº£m báº£o cÃ¡c pháº§n tá»­ trong hÃ ng ÄÆ°á»£c cÄn giá»¯a theo chiá»u dá»c */\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("		");
      out.write("body{\r\n");
      out.write("    width: 100%; \r\n");
      out.write("    background: gainsboro;\r\n");
      out.write("    position: relative; \r\n");
      out.write("    display: flex; \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("/* card */\r\n");
      out.write("\r\n");
      out.write(".card-header {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center; /* cÄn giá»¯a theo chiá»u dá»c */\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-header .btn {\r\n");
      out.write("    margin-right: 10px; /* Khoáº£ng cÃ¡ch giá»¯a cÃ¡c button */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-header .search {\r\n");
      out.write("    margin-left: auto; /* Dá»ch chuyá»n pháº§n tá»­ search sang pháº£i cÃ¹ng */\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: flex-start;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    padding: 10px 14px;\r\n");
      out.write("    border: 1px solid var(--color-text);\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card-header .search input{\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("\r\n");
      out.write("    background: #f7f7f7;\r\n");
      out.write("    font-size: 14px ;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* end */\r\n");
      out.write(".container .card{\r\n");
      out.write("    background: white;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write(".card .img-fluid {\r\n");
      out.write("    transition: transform 0.5s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card:hover .img-fluid {\r\n");
      out.write("    transform: scale(1.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container .card-body a{\r\n");
      out.write("    \r\n");
      out.write("    font-weight:400 ;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 6px 20px;\r\n");
      out.write("    font-size: 17px;\r\n");
      out.write("    color: white;\r\n");
      out.write("    border-radius: 5px;    \r\n");
      out.write("}\r\n");
      out.write(".container .card-body ul{\r\n");
      out.write("    display: block;\r\n");
      out.write("    padding-inline-start: 0;\r\n");
      out.write("    border-left: none;\r\n");
      out.write("    border-right: none;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".container .card-body .button{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content:space-around ;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* end main */");
      out.write("  \r\n");
      out.write("        ");
      out.write(".container {\r\n");
      out.write("      max-width: 1296px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .section-one {\r\n");
      out.write("      margin-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .section-one .head {\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      background-color: var(--color-two);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .section-one .add { \r\n");
      out.write("      text-align: center; \r\n");
      out.write("      padding: 20px 0;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .section-one .main-create {\r\n");
      out.write("      background-color: #FCFCF8;\r\n");
      out.write("      border: 1px solid #E6EBE7;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .section-one .main-create .wrap {\r\n");
      out.write("      padding: 50px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .section-one label {\r\n");
      out.write("      font-weight: 500;\r\n");
      out.write("    } \r\n");
      out.write("    \r\n");
      out.write("    .wrap-button{\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: space-between;\r\n");
      out.write("      margin-top: 20px; \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("	</style>   \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("        \r\n");
      out.write("    <!-- Menu sidebar -->\r\n");
      out.write("    <div class=\"menu\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <i class=\"fa-solid fa-graduation-cap\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <i class=\"fa-solid fa-house\"></i>\r\n");
      out.write("                <a href=\"#\">Tổng Quan</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <i class=\"fa-solid fa-book-open-reader\"></i>\r\n");
      out.write("                <a href=\"#\">Quản lí khoá học</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <i class=\"fa-solid fa-users\"></i>\r\n");
      out.write("                <a href=\"#\">Quản lí Người dùng</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <i class=\"fa-solid fa-file-lines\"></i>\r\n");
      out.write("                <a href=\"#\">Quản lí Đề thi</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <i class=\"fa-solid fa-spell-check\"></i>\r\n");
      out.write("                <a href=\"#\">Quản lí Từ vựng</a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("	<div class=\"main\">\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("	<div class=\"n1\">\r\n");
      out.write("		<div class=\"search\">\r\n");
      out.write("			<i class=\"fa fa-search\"></i> <input type=\"text\"\r\n");
      out.write("				placeholder=\"Tìm Kiếm\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"profile\">\r\n");
      out.write("		<i class=\"fa fa-bell\"></i> <img\r\n");
      out.write("			src=\"https://scontent.fdad1-3.fna.fbcdn.net/v/t39.30808-6/426582775_1830141884166854_7338056820026232735_n.jpg?_nc_cat=104&ccb=1-7&_nc_sid=5f2048&_nc_eui2=AeFH4S07X-xQXblT-noSx0vIgcW4HwNrjiaBxbgfA2uOJhWvDdKMeoyaPmH58ILGumQzVJpA72hfu5eu7kRpm9yp&_nc_ohc=e1f0_nPunWYQ7kNvgFFPKY5&_nc_ht=scontent.fdad1-3.fna&oh=00_AfBteHpSZtrkV7IBVrlwHsdGSEMjbCj7TF6fzf8II_ShjA&oe=663A5B5C\">\r\n");
      out.write("	</div>\r\n");
      out.write("</div> ");
      out.write("\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"section-one\"\r\n");
      out.write("				style=\"margin-top: 95px; margin-bottom: 10px;\">\r\n");
      out.write("				<div class=\"head\">\r\n");
      out.write("					<h2 class=\"add\">COUPON-COURSE</h2>\r\n");
      out.write("				</div>  \r\n");
      out.write("				<div class=\"main-create\">\r\n");
      out.write("					<div class=\"wrap\">\r\n");
      out.write("						\r\n");
      out.write("						<table class=\"table table-bordered\">\r\n");
      out.write("							<thead>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th scope=\"col\">ID</th>\r\n");
      out.write("									<th scope=\"col\">Tên Khóa Học</th>\r\n");
      out.write("									<th scope=\"col\">#</th>\r\n");
      out.write("									<th scope=\"col\">#</th>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</thead>\r\n");
      out.write("							<tbody>\r\n");
      out.write("								");

								int i = 1;
								for (Pair<CourseModel, Integer> p : (LinkedList<Pair<CourseModel, Integer>>) request.getAttribute("linkedLists")){ 
								
      out.write("\r\n");
      out.write("								<tr>\r\n");
      out.write("									<td>");
      out.print(p.getFirst().getCourseID());
      out.write("</td>\r\n");
      out.write("									<td>");
      out.print(p.getFirst().getCourseName());
      out.write("</td>\r\n");
      out.write("									<td><a href=\"#\">Xem chi tiết</a></td>\r\n");
      out.write("									<td>\r\n");
      out.write("									");
if(p.getSecond() != null){ System.out.println("aaaa" + p.getSecond());
      out.write("\r\n");
      out.write("										<form method=\"post\" action=\"/MVC/admin/coupon-course/delete\">\r\n");
      out.write("											<input type=\"hidden\" name = \"courseID\" value=\"");
      out.print(p.getFirst().getCourseID());
      out.write("\" >\r\n");
      out.write("											<input type=\"hidden\" name = \"couponID\" value=\"");
      out.print(request.getParameter("couponID"));
      out.write("\">\r\n");
      out.write("											<button type=\"submit\">Huy</button>\r\n");
      out.write("										</form>  \r\n");
      out.write("									");
} else{
      out.write(" \r\n");
      out.write("										<form method=\"post\" action=\"/MVC/admin/coupon-course/create\"> \r\n");
      out.write("											<input type=\"hidden\" name = \"courseID\" value=\"");
      out.print(p.getFirst().getCourseID());
      out.write("\" >\r\n");
      out.write("											<input type=\"hidden\" name = \"couponID\" value=\"");
      out.print(request.getParameter("couponID"));
      out.write("\">\r\n");
      out.write("											<button type=\"submit\">Ap dung</button>  \r\n");
      out.write("										</form>  \r\n");
      out.write("									");
} 
      out.write("\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>  \r\n");
      out.write("								");

								}
								
      out.write("\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("					<a href=\"/MVC/admin/coupon\">Quay Lui</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"\r\n");
      out.write("		integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("		integrity=\"sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct\"\r\n");
      out.write("		crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
